apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shopping-cart-db-pv-claim
  labels:
    app: shopping-cart-db 
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shopping-cart-db-pv-volume
  labels:
    type: local
    app: shopping-cart-db
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/shopping-cart/data"
    type: Directory